
  CREATE TABLE "GOODS_BASE" 
   (	"ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(8,2), 
	"DESCRIPTION_SHORT" VARCHAR2(100 BYTE), 
	"THUMB" BLOB, 
	"STATUS" VARCHAR2(20 BYTE), 
	"ORG_ID" VARCHAR2(50 BYTE), 
	"DEPT_ID" VARCHAR2(50 BYTE), 
	"SYS_ID" VARCHAR2(50 BYTE), 
	"SECRET_LEVEL" VARCHAR2(50 BYTE), 
	"SYS_APPLICATION_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_IP" VARCHAR2(20 BYTE), 
	"VERSION" NUMBER(16,0), 
	"ATTRIBUTE_01" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_02" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_03" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_04" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_05" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_06" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_07" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_08" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_09" DATE, 
	"ATTRIBUTE_10" DATE, 
	"ATTRIBUTE_11" NUMBER(*,0), 
	"ATTRIBUTE_12" NUMBER(*,0), 
	"ATTRIBUTE_13" NUMBER(*,0), 
	"ATTRIBUTE_14" NUMBER(*,0), 
	"ATTRIBUTE_15" NUMBER(*,0), 
	 CONSTRAINT "PK_GOODS_BASE" PRIMARY KEY ("ID")
   );
 

   COMMENT ON COLUMN "GOODS_BASE"."ID" IS 'id';
 
   COMMENT ON COLUMN "GOODS_BASE"."CODE" IS '商品编码';
 
   COMMENT ON COLUMN "GOODS_BASE"."NAME" IS '商品名称';
 
   COMMENT ON COLUMN "GOODS_BASE"."PRICE" IS '价格';
 
   COMMENT ON COLUMN "GOODS_BASE"."DESCRIPTION_SHORT" IS '商品简介';
 
   COMMENT ON COLUMN "GOODS_BASE"."THUMB" IS '缩略图';
 
   COMMENT ON COLUMN "GOODS_BASE"."STATUS" IS '商品状态';
 
   COMMENT ON COLUMN "GOODS_BASE"."ORG_ID" IS '组织ID';
 
   COMMENT ON COLUMN "GOODS_BASE"."DEPT_ID" IS '部门ID';
 
   COMMENT ON COLUMN "GOODS_BASE"."SYS_ID" IS '系统标识ID';
 
   COMMENT ON COLUMN "GOODS_BASE"."SECRET_LEVEL" IS '密级';
 
   COMMENT ON COLUMN "GOODS_BASE"."SYS_APPLICATION_ID" IS '多应用ID';
 
   COMMENT ON COLUMN "GOODS_BASE"."CREATED_BY" IS '创建人';
 
   COMMENT ON COLUMN "GOODS_BASE"."CREATION_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "GOODS_BASE"."LAST_UPDATED_BY" IS '最后修改人';
 
   COMMENT ON COLUMN "GOODS_BASE"."LAST_UPDATE_DATE" IS '最后修改时间';
 
   COMMENT ON COLUMN "GOODS_BASE"."LAST_UPDATE_IP" IS '最后更新IP';
 
   COMMENT ON COLUMN "GOODS_BASE"."VERSION" IS '版本';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_01" IS '预留字段1';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_02" IS '预留字段2';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_03" IS '预留字段3';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_04" IS '预留字段4';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_05" IS '预留字段5';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_06" IS '预留字段6';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_07" IS '预留字段7';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_08" IS '预留字段8';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_09" IS '预留字段9';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_10" IS '预留字段10';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_11" IS '预留字段11';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_12" IS '预留字段12';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_13" IS '预留字段13';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_14" IS '预留字段14';
 
   COMMENT ON COLUMN "GOODS_BASE"."ATTRIBUTE_15" IS '预留字段15';
 
   COMMENT ON TABLE "GOODS_BASE"  IS '商品基本信息';
 

 
  CREATE TABLE "GOODS_DETAIL" 
   (	"ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"GOODS_ID" VARCHAR2(50 BYTE), 
	"COLOR" VARCHAR2(50 BYTE), 
	"GOODS_SIZE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"ORG_ID" VARCHAR2(50 BYTE), 
	"DEPT_ID" VARCHAR2(50 BYTE), 
	"SYS_ID" VARCHAR2(50 BYTE), 
	"SECRET_LEVEL" VARCHAR2(50 BYTE), 
	"SYS_APPLICATION_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_IP" VARCHAR2(20 BYTE), 
	"VERSION" NUMBER(16,0), 
	"ATTRIBUTE_01" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_02" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_03" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_04" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_05" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_06" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_07" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_08" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_09" DATE, 
	"ATTRIBUTE_10" DATE, 
	"ATTRIBUTE_11" NUMBER(16,0), 
	"ATTRIBUTE_12" NUMBER(16,0), 
	"ATTRIBUTE_13" NUMBER(16,0), 
	"ATTRIBUTE_14" NUMBER(16,0), 
	"ATTRIBUTE_15" NUMBER(16,0), 
	"PROPRIETARY" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_GOODS_DETAIL" PRIMARY KEY ("ID")
   ) ;
 

   COMMENT ON COLUMN "GOODS_DETAIL"."ID" IS 'id';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."GOODS_ID" IS '商品基本信息id';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."COLOR" IS '颜色';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."GOODS_SIZE" IS '型号';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."DESCRIPTION" IS '描述';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ORG_ID" IS '组织ID';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."DEPT_ID" IS '部门ID';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."SYS_ID" IS '系统标识ID';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."SECRET_LEVEL" IS '密级';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."SYS_APPLICATION_ID" IS '多应用ID';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."CREATED_BY" IS '创建人';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."CREATION_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."LAST_UPDATED_BY" IS '最后修改人';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."LAST_UPDATE_DATE" IS '最后修改时间';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."LAST_UPDATE_IP" IS '最后更新IP';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."VERSION" IS '版本';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_01" IS '预留字段1';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_02" IS '预留字段2';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_03" IS '预留字段3';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_04" IS '预留字段4';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_05" IS '预留字段5';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_06" IS '预留字段6';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_07" IS '预留字段7';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_08" IS '预留字段8';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_09" IS '预留字段9';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_10" IS '预留字段10';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_11" IS '预留字段11';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_12" IS '预留字段12';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_13" IS '预留字段13';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_14" IS '预留字段14';
 
   COMMENT ON COLUMN "GOODS_DETAIL"."ATTRIBUTE_15" IS '预留字段15';
 
   COMMENT ON TABLE "GOODS_DETAIL"  IS '商品详细信息';
 
