
  CREATE TABLE "ORDERS" 
   (	"ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(50 BYTE), 
	"GOODS_ID" VARCHAR2(50 BYTE), 
	"GOODS_PRICE" NUMBER(8,2), 
	"GOODS_COLOR" VARCHAR2(50 BYTE), 
	"GOODS_SIZE" VARCHAR2(50 BYTE), 
	"BUYER_ID" VARCHAR2(50 BYTE), 
	"BUYER_NAME" VARCHAR2(200 BYTE), 
	"REMARK" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PAY_TIME" TIMESTAMP (6), 
	"CANCEL_TIME" TIMESTAMP (6), 
	"ORG_ID" VARCHAR2(50 BYTE), 
	"DEPT_ID" VARCHAR2(50 BYTE), 
	"SYS_ID" VARCHAR2(50 BYTE), 
	"SECRET_LEVEL" VARCHAR2(50 BYTE), 
	"SYS_APPLICATION_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_IP" VARCHAR2(20 BYTE), 
	"VERSION" NUMBER(16,0), 
	"ATTRIBUTE_01" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_02" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_03" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_04" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_05" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_06" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_07" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_08" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_09" DATE, 
	"ATTRIBUTE_10" DATE, 
	"ATTRIBUTE_11" NUMBER(16,0), 
	"ATTRIBUTE_12" NUMBER(16,0), 
	"ATTRIBUTE_13" NUMBER(16,0), 
	"ATTRIBUTE_14" NUMBER(16,0), 
	"ATTRIBUTE_15" NUMBER(16,0), 
	 CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ID")
   ) ;
 

   COMMENT ON COLUMN "ORDERS"."ID" IS 'id';
 
   COMMENT ON COLUMN "ORDERS"."CODE" IS '订单编码';
 
   COMMENT ON COLUMN "ORDERS"."GOODS_ID" IS '商品id';
 
   COMMENT ON COLUMN "ORDERS"."GOODS_PRICE" IS '商品价格';
 
   COMMENT ON COLUMN "ORDERS"."GOODS_COLOR" IS '商品颜色';
 
   COMMENT ON COLUMN "ORDERS"."GOODS_SIZE" IS '商品型号';
 
   COMMENT ON COLUMN "ORDERS"."BUYER_ID" IS '购买人id';
 
   COMMENT ON COLUMN "ORDERS"."BUYER_NAME" IS '购买人名称';
 
   COMMENT ON COLUMN "ORDERS"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "ORDERS"."STATUS" IS '订单状态';
 
   COMMENT ON COLUMN "ORDERS"."PAY_TIME" IS '支付时间';
 
   COMMENT ON COLUMN "ORDERS"."CANCEL_TIME" IS '取消时间';
 
   COMMENT ON COLUMN "ORDERS"."ORG_ID" IS '组织ID';
 
   COMMENT ON COLUMN "ORDERS"."DEPT_ID" IS '部门ID';
 
   COMMENT ON COLUMN "ORDERS"."SYS_ID" IS '系统标识ID';
 
   COMMENT ON COLUMN "ORDERS"."SECRET_LEVEL" IS '密级';
 
   COMMENT ON COLUMN "ORDERS"."SYS_APPLICATION_ID" IS '多应用ID';
 
   COMMENT ON COLUMN "ORDERS"."CREATED_BY" IS '创建人';
 
   COMMENT ON COLUMN "ORDERS"."CREATION_DATE" IS '创建时间';
 
   COMMENT ON COLUMN "ORDERS"."LAST_UPDATED_BY" IS '最后修改人';
 
   COMMENT ON COLUMN "ORDERS"."LAST_UPDATE_DATE" IS '最后修改时间';
 
   COMMENT ON COLUMN "ORDERS"."LAST_UPDATE_IP" IS '最后更新IP';
 
   COMMENT ON COLUMN "ORDERS"."VERSION" IS '版本';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_01" IS '预留字段1';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_02" IS '预留字段2';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_03" IS '预留字段3';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_04" IS '预留字段4';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_05" IS '预留字段5';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_06" IS '预留字段6';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_07" IS '预留字段7';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_08" IS '预留字段8';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_09" IS '预留字段9';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_10" IS '预留字段10';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_11" IS '预留字段11';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_12" IS '预留字段12';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_13" IS '预留字段13';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_14" IS '预留字段14';
 
   COMMENT ON COLUMN "ORDERS"."ATTRIBUTE_15" IS '预留字段15';
 
   COMMENT ON TABLE "ORDERS"  IS '订单信息';
 
